# Breast Cancer Wisconsin Diagnostic Dataset

In [24]:
import pandas as pd 
import numpy as np
import sklearn 
import matplotlib.pyplot as plt
from IPython.display import display
from sklearn.model_selection import train_test_split

## Load the data

In [25]:
from sklearn.datasets import load_breast_cancer
cancer_data = load_breast_cancer()
X = pd.DataFrame(
    cancer_data.data, 
    columns=cancer_data.feature_names) 
y = pd.Series(cancer_data.target)

In [26]:
# Display first five features
print("Features: ")
display(X.head())

# Display the first 5 target values and their name
print("Target y and Target Names:")
print(y.head())
print("Target Names:", cancer_data.target_names)

Features:

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

Target y and Target Names:
0    0
1    0
2    0
3    0
4    0
dtype: int64
Target Names: ['malignant' 'benign']

## Split the data

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle= True, 
                                                    stratify=y, random_state= 42)

print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)
print("Shape of y_train: ", y_train.shape)
print("Shape of y_test: ", y_test.shape)

Shape of X_train:  (455, 30)
Shape of X_test:  (114, 30)
Shape of y_train:  (455,)
Shape of y_test:  (114,)

## Preprocess Data

In [28]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
# Fit the scaler and transform on both training and testing data
# FIT only on TRAIN SET to prevent lakage data from the test set 
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


X_train_scaled = pd.DataFrame(
    scaler.fit_transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    scaler.transform(X_test),
    columns=X_test.columns,
    index=X_test.index
)

print("First 5 rows in original training set: ")
display(X_train.head(5))
print("First 5 rows in scaled training set: ")
display(X_train_scaled.head(5))

First 5 rows in original training set:

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
546,10.32,16.35,65.31,324.9,0.09434,0.04994,0.01012,0.005495,0.1885,0.06201,...,11.25,21.77,71.12,384.9,0.1285,0.08842,0.04384,0.02381,0.2681,0.07399
432,20.18,19.54,133.80,1250.0,0.11330,0.14890,0.21330,0.125900,0.1724,0.06053,...,22.03,25.07,146.00,1479.0,0.1665,0.29420,0.53080,0.21730,0.3032,0.08075
174,10.66,15.15,67.49,349.6,0.08792,0.04302,0.00000,0.000000,0.1928,0.05975,...,11.54,19.20,73.20,408.3,0.1076,0.06791,0.00000,0.00000,0.2710,0.06164
221,13.56,13.90,88.59,561.3,0.10510,0.11920,0.07860,0.044510,0.1962,0.06303,...,14.98,17.13,101.10,686.6,0.1376,0.26980,0.25770,0.09090,0.3065,0.08177
289,11.37,18.89,72.17,396.0,0.08713,0.05008,0.02399,0.021730,0.2013,0.05955,...,12.36,26.14,79.29,459.3,0.1118,0.09708,0.07529,0.06203,0.3267,0.06994

First 5 rows in scaled training set:

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
546,-1.072001,-0.658425,-1.088080,-0.939274,-0.135940,-1.008718,-0.968359,-1.102032,0.281062,-0.113231,...,-1.034094,-0.623497,-1.070773,-0.876534,-0.169982,-1.038836,-1.078995,-1.350527,-0.352658,-0.541380
432,1.748743,0.066502,1.751157,1.745559,1.274468,0.842288,1.519852,1.994664,-0.293045,-0.320180,...,1.228342,-0.092833,1.187467,1.104386,1.517001,0.249655,1.178594,1.549916,0.191078,-0.173739
174,-0.974734,-0.931124,-0.997709,-0.867589,-0.613515,-1.138154,-1.092292,-1.243358,0.434395,-0.429247,...,-0.973231,-1.036772,-1.008044,-0.834168,-1.097823,-1.167260,-1.282241,-1.707442,-0.307734,-1.213033
221,-0.145103,-1.215186,-0.123013,-0.253192,0.664482,0.286762,-0.129729,-0.098605,0.555635,0.029395,...,-0.251266,-1.369643,-0.166633,-0.330292,0.234006,0.096874,-0.087521,-0.344838,0.242198,-0.118266
289,-0.771617,-0.081211,-0.803700,-0.732927,-0.672282,-1.006099,-0.798502,-0.684484,0.737495,-0.457213,...,-0.801135,0.079230,-0.824381,-0.741830,-0.911367,-0.984612,-0.933190,-0.777604,0.555118,-0.761639

## Choose and train the model

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='liblinear', random_state= 42)
print("Chosen model: ", model)

Chosen model:  LogisticRegression(random_state=42, solver='liblinear')

In [30]:
# Train the model
# Fit the model on training data
model.fit(X_train_scaled, y_train)
print("Model train successfully")

Model train successfully

In [31]:
# Make decision 
y_pred = model.predict(X_test_scaled)
print("Prediction on the test set: ")
print(y_pred)
print("First 10 actual test: ")
print(y_test.head(10))
print("First 10 actual predict: ")
print(y_pred[:10])

Prediction on the test set:
[0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1
 1 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0
 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1
 0 1 1]
First 10 actual test:
256    0
428    1
501    0
363    1
564    0
464    1
358    1
343    0
516    0
567    0
dtype: int64
First 10 actual predict:
[0 1 0 1 0 1 1 0 0 0]

## Evaluated the model

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.6f}")
# Generated the classification report (precision, f1-score per class)
class_report = classification_report(y_test, y_pred, 
                                     target_names=cancer_data.target_names)
print("Classification Report:\n")
print(class_report)
# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix")
print("Rows: True Lables")
print("Columns: Predict Lables")
print(pd.DataFrame(conf_matrix, 
                   index=cancer_data.target_names, 
                   columns=cancer_data.target_names))

Accuracy: 0.982456
Classification Report:

              precision    recall  f1-score   support

   malignant       0.98      0.98      0.98        42
      benign       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

Confusion Matrix
Rows: True Lables
Columns: Predict Lables
           malignant  benign
malignant         41       1
benign             1      71

## Tune Hyperparameters

In [33]:
# Can be use Grid Search or Random Search 
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer, recall_score

# Define parameter grid to search 
# small C -> strong penalty
# large C -> weak penalty 
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100], 
    'solver': ['liblinear', 'lbfgs']
    }

grid_search = GridSearchCV(LogisticRegression(random_state= 42), 
                           param_grid, cv= 5, 
                           scoring=make_scorer(recall_score, pos_label=0))
grid_search.fit(X_train_scaled, y_train)

print("Best parameters found:", grid_search.best_params_)
print(f"Best Cross - Validation Accuracy: {grid_search.best_score_:.6f}")
# Get the best model 
best_model = grid_search.best_estimator_
# Evaluate the best model on the test set
y_pred_tuned = best_model.predict(X_test_scaled)
accuracy_tuned = accuracy_score(y_test, y_pred_tuned)
print(f"Accuracy with Tuned Model on the test set: {accuracy_tuned:.4f}")

# Get Clasification Report on Tuned Model
print("Classification Report on Tuned Model")
print(classification_report(y_test, y_pred_tuned, 
                            target_names= cancer_data.target_names))

Best parameters found: {'C': 1, 'solver': 'liblinear'}
Best Cross - Validation Accuracy: 0.964706
Accuracy with Tuned Model on the test set: 0.9825
Classification Report on Tuned Model
              precision    recall  f1-score   support

   malignant       0.98      0.98      0.98        42
      benign       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114